### ISSUE TITLE
程序不能使用了，报错了，重新安装也无法使用

### ISSUE THREAD

**Issue by liuhaohaoha** [lyj0309/chaoxing-xuexitong-autoflush#2]
报错内容：
syntaxError：Unexpected token< in JSON at position 0
       at JSON.parse (<anonymous>)
       at Player. doTick (C:\Users\lenovo\chaoxing-xuexitong-antoflush\player.js;48:23)
       at processTicksAndRe jections (internal/process/task_queues.js:95:5)
       at async Player.eventLoop (C:\Users\leovo\chaoxing-xuexitong-autoflush\player.js:104:9)

小白一枚，求大佬解决~~~ @lyj0309

**Comment by lyj0309** [comment]
直接下载exe用吧

**Comment by liuhaohaoha** [comment]
> 直接下载exe用吧
就是在exe里运行，到没有刷过的章节那里，就来回闪这几行代码，昨天晚上还正常运行，可能是电脑休眠了一下，今天上午就没法用了，重启，重装git和node和cx.exe貌似没什么用

**Comment by lyj0309** [comment]
> > 直接下载exe用吧
> > @lyj0309 就是在exe里运行，到没有刷过的章节那里，就来回闪这几行代码，昨天晚上还正常运行，可能是电脑休眠了一下，今天上午就没法用了，重启，重装git和node和cx.exe貌似没什么用

的确是个bug，最近比较忙，等修复吧

**Comment by lyj0309** [comment]
已经修复
